#ifndef INTERFACES_HPP
#define INTERFACES_HPP

//
// IUSBHardwareDevice
//
#define DEFINE_ABSTRACT_USBXHCIHARDWARE()

#define IMP_IUSBXHCIHARDWARE

DECLARE_INTERFACE_(IXHCIHardwareDevice, IUSBHardwareDevice)
{
    DEFINE_ABSTRACT_UNKNOWN();
    DEFINE_ABSTRACT_USBHARDWAREDEVICE();
    DEFINE_ABSTRACT_USBXHCIHARDWARE();
};

typedef IXHCIHardwareDevice *PXHCIHARDWAREDEVICE;

//
// IUSBRequest
//
#define DEFINE_ABSTRACT_USBXHCIREQUEST()

#define IMP_IXHCIREQUEST

DECLARE_INTERFACE_(IXHCIRequest, IUSBRequest)
{
    DEFINE_ABSTRACT_UNKNOWN();
    DEFINE_ABSTRACT_USBREQUEST();
    DEFINE_ABSTRACT_USBXHCIREQUEST();
};

typedef IXHCIRequest *PXHCIREQUEST;

//
// IUSBQueue
//
#define DEFINE_ABSTRACT_USBXHCIQUEUE()

#define IMP_IXHCIQUEUE

DECLARE_INTERFACE_(IXHCIQueue, IUSBQueue)
{
    DEFINE_ABSTRACT_UNKNOWN();
    DEFINE_ABSTRACT_USBQUEUE();
    DEFINE_ABSTRACT_USBXHCIQUEUE();
};

typedef IXHCIQueue *PXHCIQUEUE;
#endif // INTERFACES_HPP
